3144659 datetime storage timezone
palantirnet/drupal-rector pull request #105
Opened 2020-06-03 00:42 UTC by dww

Should apply cleaning on top of the other PR.

2020-06-03 00:43 UTC, dww commented
Or is it better to cleanly put this commit in the other CR and close this?

2020-06-03 03:02 UTC, damontgomery requested changes
Thanks again, @dww.

Either one PR or multiple is OK with me. If it's OK with you and there are merge conflicts between multiple PRs, I can try to push changes to your fork to resolve them before merging in the code.

For this PR (similar to the other), I want to avoid confusion, particularly with examples that aren't functional. I'm not sure that it would cause issues with Rector, but I think people might be confused by the example if it includes references to variables that were never created, etc. I'd rather we only include simple examples than add additional ones that are confusing.

Can you check the comments and let me know if you have suggestions / questions?

Thanks again.

2020-06-03 03:02 UTC, damontgomery commented on rector_examples/datetime_storage_timezone.php
> +  $now->setTimezone(new \DateTimeZone(DATETIME_STORAGE_TIMEZONE));
Can you define $now so that this is valid code?

2020-06-03 03:02 UTC, damontgomery commented on src/Rector/Deprecation/DatetimeStorageTimezoneRector.php
> +$now->setTimezone(new \DateTimeZone(DATETIME_STORAGE_TIMEZONE));
Can you define $now in this example or use the simple `$timezone = DATETIME_STORAGE_TIMEZONE` example? Same for the after.

2020-06-04 02:44 UTC, dww commented
Sorry, I screwed up my forked repo a bit.  I'll open a new PR with clean commits now that the other PR is merged.  I'll fix these comments there, too.  Thanks!

2020-06-04 02:44 UTC, closed without merging