Adds AssertLegacy and other new items to the index.
palantirnet/drupal-rector pull request #170
Opened 2021-08-12 18:59 UTC by agentrickard

## Description

Adds items to the deprecation-index.yml file that are needed for Update Status.

## To Test
- Needs to be tested as a replacement for the patch in https://www.drupal.org/project/upgrade_status/issues/3224920

## Drupal.org issue

https://www.drupal.org/project/rector/issues/3224919

2021-08-12 19:27 UTC, agentrickard commented
Notes:

- PassRector.php is incorrectly documented.

2021-08-12 19:47 UTC, agentrickard commented
See also https://www.drupal.org/project/rector/issues/3227957

2021-08-18 19:13 UTC, mglaman commented
The `push` failure for drupal_rector_sandbox will be fixed by https://github.com/palantirnet/drupal-rector/pull/172 and a rebase when merged.

2021-08-18 19:17 UTC, mglaman requested changes

2021-08-18 19:17 UTC, mglaman commented on deprecation-index.yml
> +    PHPStan: 'Deprecated in drupal:8.5.0 and is removed from drupal:10.0.0. Use $element->findAll('xpath', 'option') instead.'
We have to double quote the string since it has single quotes in the deprecation message.

2021-08-18 19:22 UTC, mglaman commented on deprecation-index.yml
> +    PHPStan: 'Deprecated in drupal:8.5.0 and is removed from drupal:10.0.0. Use $element->findAll('xpath', 'option') instead.'
@agentrickard made a fix in https://github.com/palantirnet/drupal-rector/pull/172, this is a PR to your branch so it'll update this PR

2021-08-24 16:02 UTC, agentrickard commented
@mglaman This is fixed up as best we have right now. @goba had noted a few of these items are not listed in PHPStan at all.

2021-08-25 19:39 UTC, mglaman approved these changes

2021-08-25 19:40 UTC, mglaman commented
Looks good to me!

2021-08-27 20:03 UTC, merged