Issue #3277704: Remove PHPUNIT_75 constant in Rector
palantirnet/drupal-rector pull request #197
Opened 2022-04-28 14:23 UTC by FlorentTorregrosa

## Description
Remove usage of non-existing constant in rector 0.12.22

## Drupal.org issue
https://www.drupal.org/project/rector/issues/3277704

2022-05-03 15:53 UTC, mglaman requested changes

2022-05-03 15:53 UTC, mglaman commented on config/drupal-8/drupal-8-all-deprecations.php
> -    $containerConfigurator->import(PHPUnitSetList::PHPUNIT_75);
What is the replacement? We need this as it fixes PHPUnit code for folks.

2022-05-03 15:53 UTC, mglaman commented on config/drupal-8/drupal-8-all-deprecations.php
> -    $containerConfigurator->import(PHPUnitSetList::PHPUNIT_75);
What is the replacement? We need this as it fixes PHPUnit code for folks.

2022-05-03 21:25 UTC, mglaman commented
We can work on this once https://github.com/palantirnet/drupal-rector/pull/195 lands and is green. This was removed in a patch release without deprecation.

2022-05-03 21:25 UTC, mglaman commented on config/drupal-8/drupal-8-all-deprecations.php
> -    $containerConfigurator->import(PHPUnitSetList::PHPUNIT_75);
Answering for myself:

There is no replacement value. Removed in rector/rector-phpunit:0.11.26 due to it being a complex upgrade path.

2022-05-18 19:22 UTC, mglaman commented
If this was rebased against `main`, it should pass. I cannot do that, however.

2022-05-22 15:33 UTC, FlorentTorregrosa commented
Hi,

Thanks @mglaman for your review.

PR rebased

2022-05-23 10:18 UTC, mglaman approved these changes

2022-05-24 14:40 UTC, merged

2022-05-24 15:19 UTC, FlorentTorregrosa commented
Thanks for the merge :)