Feature/9.3 taxonomy rectors
palantirnet/drupal-rector pull request #254
Opened 2023-09-08 11:02 UTC by bbrala

## Description
Made a few rectors for: https://www.drupal.org/node/3039041

When the FunctionToStaticCallRector is merged, we can remove one of the implementation from this one ni favor of a confgiured rule.

## To Test
Unit and functional tests

## Drupal.org issue
Provide a link to the issue from https://www.drupal.org/project/rector/issues. If no issue exists, please create one and link to this PR.

2023-09-08 12:04 UTC, bbrala commented
There are 2 failures left, but im not sure we can actually find those. Those assume we know something is a `Term` instance, which seems kinda optimistic?

2023-09-23 12:53 UTC, bbrala commented
Implemented the optimistic approach, since the code would have been broken already if it was not a term.

2023-09-23 12:56 UTC, bbrala commented
This needs to wait for deprecated fixes, since this will need to implement the versioned configuration.

2023-10-31 20:11 UTC, agentrickard requested changes
Needs a minor update

2023-10-31 20:11 UTC, agentrickard commented on config/drupal-9/drupal-9.3-deprecations.php
> +        new FunctionToStaticConfiguration('taxonomy_implode_tags', 'Drupal\Core\Entity\Element\EntityAutocomplete', 'getEntityLabels'),
New class params 
```    
    /**
     * @param string $introducedVersion Introduced version of this change
     * @param string $deprecatedFunctionName Deprecated function name
     * @param string $className Class to call static method on
     * @param string $methodName Method to call statically
     * @param array|int[] $argumentReorder Reorder arguments array[old_position] = new_position
     */
```

2023-10-31 20:26 UTC, agentrickard approved these changes

2023-11-01 08:23 UTC, merged