Initial file_scan_directory rule
palantirnet/drupal-rector pull request #39
Opened 2020-04-16 04:25 UTC by shaal

[WIP]

@damontgomery according to the change-record, https://www.drupal.org/node/3038437
We should embed this inside a new `if` statement.
Do you know how can we implement that with Rector?

2020-04-16 16:27 UTC, damontgomery requested changes
Overall this makes sense to me. Do we want to move forward without the `if` statement and come back to that later? I don't think it would be needed in most cases.

2020-04-16 16:27 UTC, damontgomery commented on rector_examples/file_scan_directory.php
> +  ];
Is this WIP code? I would set the options rather than merging arrays.

2020-04-16 16:27 UTC, damontgomery commented on src/Rector/Deprecation/FileScanDirectoryRector.php
> +     * Replaces deprecated file_scan_directory() calls.
Can you fix this spacing?

2020-04-16 16:27 UTC, damontgomery commented on src/Rector/Deprecation/FileScanDirectoryRector.php
> + * - Dependency injection
Can you add a comment about adding the if() statement?

2020-05-07 16:49 UTC, Kbentham commented
I have merged in master and updated this pr to account for all of the changes and dan's feedback.

2020-05-08 15:44 UTC, merged

2020-05-08 15:45 UTC, damontgomery commented
Thanks @Kbentham and @shaal!